// ---------------------------------------------------------------
// Pulls essays from a Notion database and writes content/essays.json
// in the shape the site expects. Zero npm dependencies — uses the
// Notion REST API directly via the built-in fetch (Node 18+).
//
// Usage:
//   NOTION_TOKEN=secret_xxx NOTION_DATABASE_ID=xxxx node scripts/sync-notion.mjs
//
// Wiring it up for "auto-refresh":
//   1. Deploy this site to Vercel (or Netlify) as a static site.
//   2. Create a Deploy Hook in your Vercel project settings — this
//      gives you a URL that triggers a fresh build when called.
//   3. In Notion, add an automation (or a small Zapier/Make zap)
//      that fires that Deploy Hook URL whenever a page in the
//      database is edited/published.
//   4. Add this script as your project's "build command" (or a
//      prebuild step) so every deploy re-pulls the latest Notion
//      content before the static files are published:
//        "build": "node scripts/sync-notion.mjs && echo done"
//   That gives you edit-in-Notion -> auto-refreshed live site
//   within a few minutes, with no server to run yourself.
// ---------------------------------------------------------------

const TOKEN = process.env.NOTION_TOKEN;
const DB_ID = process.env.NOTION_DATABASE_ID;

if (!TOKEN || !DB_ID) {
  console.log(
    "NOTION_TOKEN / NOTION_DATABASE_ID not set — skipping Notion sync and keeping the existing content/essays.json as-is."
  );
  process.exit(0);
}

const NOTION_VERSION = "2022-06-28";

async function notion(path, options = {}) {
  const res = await fetch(`https://api.notion.com/v1${path}`, {
    ...options,
    headers: {
      Authorization: `Bearer ${TOKEN}`,
      "Notion-Version": NOTION_VERSION,
      "Content-Type": "application/json",
      ...(options.headers || {}),
    },
  });
  if (!res.ok) {
    throw new Error(`Notion API ${path} failed: ${res.status} ${await res.text()}`);
  }
  return res.json();
}

function plainText(richTextArr = []) {
  return richTextArr.map((t) => t.plain_text).join("");
}

// Maps a Notion page's blocks into the { type, text/rows } shape
// the site's essay.js renderer expects.
async function blocksToBody(pageId) {
  const body = [];
  let cursor;
  do {
    const res = await notion(
      `/blocks/${pageId}/children?page_size=100${cursor ? `&start_cursor=${cursor}` : ""}`
    );
    for (const block of res.results) {
      if (block.type === "heading_2" || block.type === "heading_3") {
        body.push({ type: "h2", text: plainText(block[block.type].rich_text) });
      } else if (block.type === "quote") {
        body.push({ type: "pull", text: plainText(block.quote.rich_text) });
      } else if (block.type === "paragraph") {
        const text = plainText(block.paragraph.rich_text);
        if (text.trim()) body.push({ type: "p", text });
      } else if (block.type === "table") {
        // Notion tables need a follow-up call for rows; skipped here for
        // brevity — hand-author table blocks directly in essays.json for
        // now, or extend this function if you need Notion-authored tables.
      }
    }
    cursor = res.has_more ? res.next_cursor : undefined;
  } while (cursor);
  return body;
}

function prop(page, name) {
  return page.properties[name];
}

async function main() {
  const results = [];
  let cursor;
  do {
    const res = await notion(`/databases/${DB_ID}/query`, {
      method: "POST",
      body: JSON.stringify(cursor ? { start_cursor: cursor } : {}),
    });
    results.push(...res.results);
    cursor = res.has_more ? res.next_cursor : undefined;
  } while (cursor);

  const essays = [];
  for (const page of results) {
    const title = plainText(prop(page, "Title")?.title || []);
    if (!title) continue;
    const slug = plainText(prop(page, "Slug")?.rich_text || []) || title.toLowerCase().replace(/[^a-z0-9]+/g, "-");
    const status = (prop(page, "Status")?.select?.name || "progress").toLowerCase().includes("live")
      ? "live"
      : "progress";
    const category = prop(page, "Category")?.select?.name || "Strategy";
    const order = prop(page, "Order")?.number ?? 99;
    const teaser = plainText(prop(page, "Teaser")?.rich_text || []);
    const dek = plainText(prop(page, "Dek")?.rich_text || []) || teaser;
    const wordCountTarget = prop(page, "Word Count")?.number || 0;
    const hasDraft = !!prop(page, "Has Draft")?.checkbox;

    const body = hasDraft ? await blocksToBody(page.id) : [];

    essays.push({
      id: slug,
      order,
      title,
      category,
      status,
      hasDraft,
      wordCountTarget,
      teaser,
      dek,
      body,
    });
  }

  const { writeFileSync } = await import("fs");
  writeFileSync(
    "content/essays.json",
    JSON.stringify(
      {
        _comment: "Auto-generated by scripts/sync-notion.mjs — do not hand-edit.",
        essays,
      },
      null,
      2
    )
  );
  console.log(`Synced ${essays.length} essays from Notion into content/essays.json`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
